/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg43_01_nagy_feladat_recept_konyv;

import javax.swing.JOptionPane;

/**
 *
 * @author takac
 */
public class HozzavaloDialog extends javax.swing.JDialog {
    
    
    private Hozzavalo hozzavalo;
 
    public HozzavaloDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public HozzavaloDialog(java.awt.Dialog parent, Hozzavalo hozzavalo) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        this.hozzavalo = hozzavalo;
        tfMennyiseg.setText("" + this.hozzavalo.getMennyiseg());
        tfMertekegyseg.setText(this.hozzavalo.getMertekegyseg());
        tfAlapanyag.setText(this.hozzavalo.getAlapanyag());
        tfAr.setText("" + this.hozzavalo.getAr());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfMennyiseg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfMertekegyseg = new javax.swing.JTextField();
        tfAr = new javax.swing.JTextField();
        tfAlapanyag = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btOke = new javax.swing.JButton();
        btMegsem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kérem írja be 1 adag elkészítéshez szükséges hozzávalókat!");
        jLabel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mértékegység(max. 45 karakter)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Alapanyag(max. 45 karakter)");

        tfMennyiseg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ára(Ft)");

        tfMertekegyseg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tfAr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tfAlapanyag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hozzávalók:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mennyiség");

        btOke.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btOke.setText("Oké");
        btOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkeActionPerformed(evt);
            }
        });

        btMegsem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMegsem.setText("Mégsem");
        btMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMegsemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMennyiseg)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btMegsem)
                                    .addComponent(tfMertekegyseg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAlapanyag, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btOke, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfAr, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btMegsem, btOke});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlapanyag)
                    .addComponent(tfMertekegyseg)
                    .addComponent(tfMennyiseg))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOke, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMegsem))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btMegsem, btOke});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkeActionPerformed
        if(tfMennyiseg.getText().isEmpty() || tfMertekegyseg.getText().isEmpty() || tfAlapanyag.getText().isEmpty() || tfAr.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Kérem töltse ki az üres helyeket vagy nyomja meg a 'Mégsem' gombot!", "Hiba", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(tfMertekegyseg.getText().length() > 45) {
            JOptionPane.showMessageDialog(rootPane, "A '" + tfMertekegyseg.getText() + "' nagyobb 45 karakternél!", "Hiba!", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (tfAlapanyag.getText().length() > 45) {
            JOptionPane.showMessageDialog(rootPane, "A '" + tfAlapanyag.getText() + "' nagyobb 45 karakternél!", "Hiba!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        double mennyiseg = 0;
        int ar = 0;
        try {
         mennyiseg = Double.parseDouble(tfMennyiseg.getText());
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Kérem számot írjon be az 'Mennyiség'-hez!", "Hiba!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(mennyiseg == 0) {
            JOptionPane.showMessageDialog(rootPane, "Nullát nem adhat a 'Mennyiség'-hez!", "Hiba!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
         ar = Integer.parseInt(tfAr.getText());
            if (this.hozzavalo != null) {
                this.hozzavalo.setMennyiseg(mennyiseg);
                this.hozzavalo.setMertekegyseg(tfMertekegyseg.getText());
                this.hozzavalo.setAlapanyag(tfAlapanyag.getText());
                this.hozzavalo.setAr(ar);
            } else {
                this.hozzavalo = new Hozzavalo(mennyiseg, tfMertekegyseg.getText(), tfAlapanyag.getText(), ar);
            }
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Kérem egész számot írjon be az 'Ára'-hoz!", "Hiba!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        this.setVisible(false);
    }//GEN-LAST:event_btOkeActionPerformed

    private void btMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMegsemActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btMegsemActionPerformed
    
    public Hozzavalo getHozzavalo() {
        return this.hozzavalo;
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMegsem;
    private javax.swing.JButton btOke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfAlapanyag;
    private javax.swing.JTextField tfAr;
    private javax.swing.JTextField tfMennyiseg;
    private javax.swing.JTextField tfMertekegyseg;
    // End of variables declaration//GEN-END:variables
}
